export const ERROR_CODES = {
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  NOT_FOUND: 'NOT_FOUND',
  HAS_DEPENDENCIES: 'HAS_DEPENDENCIES',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_INPUT: 'INVALID_INPUT',
  NOT_VERIFIED: 'NOT_VERIFIED',
  EXPIRED: 'EXPIRED',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
} as const;