export const ERROR_CODES = {
  PARISH_ALREADY_EXISTS: 'PARISH_ALREADY_EXISTS',
  CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',
  USER_ALREADY_EXISTS_ERROR: 'USER_ALREADY_EXISTS_ERROR',
  INVALID_CREDENTIALS_ERROR: 'INVALID_CREDENTIALS_ERROR',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  EMAIL_NOT_FOUND: 'EMAIL_NOT_FOUND',
  TOKEN_EXPIRED_ERROR: 'TOKEN_EXPIRED_ERROR',
  VERIFICATION_TOKEN_NOT_FOUND: "VERIFICATION_TOKEN_NOT_FOUND"
} as const;