export const ERROR_CODES = {
  PARISH_ALREADY_EXISTS: 'PARISH_ALREADY_EXISTS',
  CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',
  USER_ALREADY_EXISTS_ERROR: 'USER_ALREADY_EXISTS_ERROR',
  INVALID_CREDENTIALS_ERROR: 'INVALID_CREDENTIALS_ERROR',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED'
} as const;